name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package

      - name: Build Docker image
        run: docker build -t romanbarchuk/integrity_check_repository .

      - name: Log in to Docker registry  
        env: 
            USER: ${{ secrets.DOCKERHUB_USERNAME }}
            PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }} 
        run: | 
          docker login -u $USER -p $PASSWORD
      - name: Push Docker image
        run: docker push romanbarchuk/integrity_check_repository
